spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  # API meteorológica para Sevilla (España), sin tokens ni bloqueos cloud
  api:
    url: "https://open-meteo.com"
  kafka:
    topic: "spain-weather-topic"
